# -*- mode: ruby -*- 
# vi: set ft=ruby :
disk1 = './disk-0-1.vdi'
disk2 = './disk-0-2.vdi'
disk3 = './disk-0-3.vdi'
Vagrant.configure("2") do |config|
    # Base VM OS configuration.
    config.ssh.insert_key = false
    config.vm.synced_folder '.', '/vagrant', disabled: true
    # General VirtualBox VM configuration.
    config.vm.provider :virtualbox do |v|
      v.gui = true
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  
    # rocky box 1.
    config.vm.define "rocky1" do |rocky1|
      rocky1.vm.hostname = "RockyBox1"
      rocky1.vm.network :private_network, ip: "192.168.2.100"
      config.vm.box = "cobra-cli/Rocky9GUI"
      config.ssh.insert_key = false
      rocky1.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--accelerate3d", "off"]
      end
    config.vm.synced_folder ".", "/vagrant", type: "rsync",
      rsync__exclude: ".git/"
#    config.vm.provision "ansible_local" do |ansible|
#      ansible.playbook = "playbook.yml"
    end

    config.vm.define "rocky2" do |rocky2|
      rocky2.vm.hostname = "RockyBox2"
      rocky2.vm.network :private_network, ip: "192.168.2.101"
      config.vm.box = "cobra-cli/Rocky9GUI"
      config.ssh.insert_key = false
      rocky2.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--accelerate3d", "off"]
        unless File.exist?(disk1)
          v.customize ['createhd', '--filename', disk1, '--variant', 'Fixed', '--size', 2 * 1024]
          v.customize ['createhd', '--filename', disk2, '--variant', 'Fixed', '--size', 5 * 1024]
          v.customize ['createhd', '--filename', disk3, '--variant', 'Fixed', '--size', 1 * 1024]
          v.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', disk1]
        v.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 3, '--device', 0, '--type', 'hdd', '--medium', disk2]
        v.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 4, '--device', 0, '--type', 'hdd', '--medium', disk3]
      end
    config.vm.synced_folder ".", "/vagrant", type: "rsync",
      rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", "disk-0-3.vdi"]
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook2.yml"
    end
  end
end
end
